apiVersion: v1
kind: Service
metadata:
  name: banking-auth-service
  namespace: banking
  labels:
    app: banking-auth-service
spec:
  type: ClusterIP
  selector:
    app: banking-auth-service
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
